# Generated by Django 5.0.6 on 2024-05-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
